on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ 'x64', 'x86' ]
        standalone: [ true, false ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Build Exe
        working-directory: ./Traincrew_depMelody
        run: |
          dotnet publish -c Release \
            -o ../out \
            -r win-${{ matrix.platform }} \
            -p:PublishSingleFile=true \
            -p:EnableWindowsTargeting=true \
            --self-contained ${{ matrix.standalone }}
      - name: Zip binaries
        run: |
          cd out
          zip -r out.zip .
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out.zip
          asset_name: Traincrew_depMelody-${{ matrix.platform }}${{ (matrix.standalone && '-standalone') || '' }}.zip
          tag: latest
          overwrite: true